### ISSUE TITLE
Simple api bug with bows in multiplayer

### ISSUE THREAD

**Issue by necanthrope** [AleXndrTheGr8st/SimpleCore#2]
Hi!  First of all, this is a great mod, and I am really enjoying using it. :)

I have discovered an issue with the simple bow, however.  In multiplayer, when I attempt to fire an arrow, the client crashes.  The server keeps running, and upon reconnect, I still have the bow object.

This doesn't happen in single player. I have to wonder if it's an issue with the version of Forge I'm running; maybe you wrote to a different version, where a message sent to the client has a property as an float instead of an integer. I'm currently running under version 1291.

Here is the stack trace:

[13:46:03] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
    at alexndr.api.content.items.SimpleBow.func_77615_a(SimpleBow.java:288) ~[SimpleBow.class:?]
    at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:402) ~[add.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71034_by(EntityPlayer.java:196) ~[yz.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78766_c(PlayerControllerMP.java:449) ~[bje.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1906) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by LemADEC** [comment]
What kind of bow was involved? did you try other bow types?

**Comment by necanthrope** [comment]
I don't remember!  I'll try to figure it out tonight.  I think it was the one with knockback.  (onyx?)

**Comment by Skrallexxx** [comment]
Known bug, fixed in next update.
