### ISSUE TITLE
Sinsinite bow crash

### ISSUE THREAD

**Issue by LemADEC** [AleXndrTheGr8st/SimpleCore#3]
The Sinsinite bow crashes the game when player tries to use it:

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 04/08/15 22:02
Description: Ticking memory connection

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
    at alexndr.api.content.items.SimpleBow.func_77615_a(SimpleBow.java:288)
    at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:402)
    at net.minecraft.entity.player.EntityPlayer.func_71034_by(EntityPlayer.java:196)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:439)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at alexndr.api.content.items.SimpleBow.func_77615_a(SimpleBow.java:288)
    at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:402)
    at net.minecraft.entity.player.EntityPlayer.func_71034_by(EntityPlayer.java:196)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:439)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@6c296df7
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
    Memory: 1457356456 bytes (1389 MB) / 2539651072 bytes (2422 MB) up to 4151836672 bytes (3959 MB)
    JVM Flags: 27 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m -XX:ThreadPriorityPolicy=42 -XX:+TieredCompilation -XX:TargetSurvivorRatio=90 -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=15 -XX:+UnlockExperimentalVMOptions -XX:+UseBiasedLocking -XX:UseSSE=3 -XX:+UseCodeCacheFlushing -XX:+UseThreadPriorities -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+ReduceSignalUsage -XX:+UseInterpreter -XX:+UseFastEmptyMethods -XX:+UseSharedSpaces -XX:AllocatePrefetchStyle=1 -XX:+AlwaysCompileLoopMethods -XX:SharedReadOnlySize=30m -XX:+RewriteFrequentPairs -XX:+OptimizeStringConcat -XX:+CMSCleanOnEnter -XX:+UseSplitVerifier -XX:+UseInlineCaches
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 1, tcache: 83, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 80 mods loaded, 80 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
    UCHIJAAAA   Forge{10.13.4.1492} [Minecraft Forge] (modpack.jar) 
    UCHIJAAAA   AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) 
    UCHIJAAAA   MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJAAAA   gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.00.50.jar) 
    UCHIJAAAA   IC2{2.2.757-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.757-experimental.jar) 
    UCHIJAAAA   ImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1.jar) 
    UCHIJAAAA   AdvancedRepulsionSystems{59.0.3} [Advanced Repulsion Systems] (adv-repulsion-systems-59.0.3.jar) 
    UCHIJAAAA   AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) 
    UCHIJAAAA   AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCHIJAAAA   simplecore{1.1.0} [SimpleCore API] (SimpleCore-API-1.1.0.jar) 
    UCHIJAAAA   akkamaddicore{1.7.10-2.0.0} [akkamaddi's Core API] (akkamaddiCore-1.7.10-2.0.0.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   fusion{1.6.0} [Fusion] (Fusion-1.6.0.jar) 
    UCHIJAAAA   simpleores{1.6.0} [SimpleOres 2] (SimpleOres2-1.6.0.jar) 
    UCHIJAAAA   arsenic{1.7.10-1.5.0} [Simple Arsenic and Old Lace] (ArsenicAndLace-1.7.10-1.5.0.jar) 
    UCHIJAAAA   arsmagica2{1.4.0.008} [Ars Magica 2] (ArsMagica2-1.4.0.008.jar) 
    UCHIJAAAA   XaeroBetterPvP{1.5.7} [Better PVP Mod] (BetterPvP_1.5.7_1.7.10_Forge.jar) 
    UCHIJAAAA   chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
    UCHIJAAAA   ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
    UCHIJAAAA   classicalalchemy{1.7.10-1.5.1} [Classical Alchemy] (ClassicalAlchemy-1.7.10-1.5.1.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
    UCHIJAAAA   cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    UCHIJAAAA   creativecore{1.2.0} [CreativeCore] (CreativeCore-v1.2.2 mc1.7.10.jar) 
    UCHIJAAAA   simplecthon{1.7.10-1.5.2} [Simple Cthon] (cthon-1.7.10-1.5.2.jar) 
    UCHIJAAAA   Cyan Warrior Swords Mod{2.1.1} [Cyan Warrior Swords Mod] (Cyan_Warrior_Swords_Mod_v.2.1.1.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
    UCHIJAAAA   TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.1-17.jar) 
    UCHIJAAAA   ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
    UCHIJAAAA   fastleafdecay{1.1} [Fast Leaf Decay] (fastleafdecay-1.1.jar) 
    UCHIJAAAA   FinndusFillies{2.1.0.12} [Finndus Fillies] (FinndusFillies-1.7.10-universal-2.1.0.12.jar) 
    UCHIJAAAA   gvc{0.6.1} [§aGliby's§f Voice Chat Mod] (GlibysVC-1.7.10-0.6.1.jar) 
    UCHIJAAAA   goldenglitter{1.7.10-1.5.0} [Golden Glitter] (goldenglitter-1.7.10-1.5.0.jar) 
    UCHIJAAAA   UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.7.jar) 
    UCHIJAAAA   gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.00.50.jar) 
    UCHIJAAAA   haditecoal{1.7.10-1.5.1} [Hadite Coal] (hadite-1.7.10-1.5.1.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.4.4} [Immersive Engineering] (ImmersiveEngineering-0.4.4.jar) 
    UCHIJAAAA   InvisibLights{2.3-7} [InvisibLights] (InvisibLights-2.3-7.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   jsonables{1.0.9} [JSONAbles] (JSONAbles-1.0.9.jar) 
    UCHIJAAAA   mcheli{0.10.7} [MC Helicopter] (mcheli) 
    UCHIJAAAA   MemoryCleaner{1.0} [Memory Cleaner] (MemoryCleaner-1.4-mc.1.7.10.jar) 
    UCHIJAAAA   ModularArmour{1.0.0} [Modular Armour] (ModularArmour-1.7.10-1.0.17-40.jar) 
    UCHIJAAAA   NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
    UCHIJAAAA   notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) 
    UCHIJAAAA   neresources{0.1.0.106} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.106.jar) 
    UCHIJAAAA   numina{0.4.0.87} [Numina] (Numina-0.4.0.87.jar) 
    UCHIJAAAA   onlysilver{1.9.4-1.7.2} [OnlySilver] (OnlySilver-1.9.4-1.7.2.jar) 
    UCHIJAAAA   openmodularturrets{2.1.3-163} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.3-163.jar) 
    UCHIJAAAA   MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   simplecobalt{1.7.10-1.5.1} [Simple Cobalt] (simplecobalt-1.7.10-1.5.1.jar) 
    UCHIJAAAA   simpletungsten{1.7.10-1.5.5} [Simple Tungsten] (simpletungsten-1.7.10-1.5.5.jar) 
    UCHIJAAAA   steelyglint{1.7.10-1.5.2} [Steely Glint] (SteelyGlint-1.7.10-1.5.2.jar) 
    UCHIJAAAA   stefinusguns{0.5.2} [New Stefinus Guns] (Stefinus Guns-0.5.2.jar) 
    UCHIJAAAA   sterlingandblack{1.7.10-1.5.2} [Sterling and Black] (SterlingAndBlack-1.7.10-1.5.2.jar) 
    UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHIJAAAA   TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
    UCHIJAAAA   Turbo{1.2.0} [ï¿½eï¿½nMinecraft Turbo] (Turbo-1.7.10-1.2.0.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJAAAA   WTFCore{1.41} [WTFCore] (WTFMods_Test2.jar) 
    UCHIJAAAA   CaveBiomes{1.21} [WhiskyTangoFox's Cave Biomes] (WTFMods_Test2.jar) 
    UCHIJAAAA   WTFTweaks{1.21} [WhiskyTangoFox's Tweaks] (WTFMods_Test2.jar) 
    UCHIJAAAA   WTFOres{1.2} [WhiskyTangoFox's Ores] (WTFMods_Test2.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['RAGER_101'/311, l='New World', x=391.47, y=78.51, z=-351.34]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by LemADEC** [comment]
This is reproduced in single player.

**Comment by Skrallexxx** [comment]
Known bug, will be fixed in next update.
